[project]
name = "pytictactoe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "art>=6.4",
    "pynput>=1.8.1",
    "rich>=13.9.4",
]
